# Generated by Django 4.1.3 on 2023-10-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobseeker_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='employer',
            new_name='job_employer',
        ),
    ]
